// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CreateAutomation(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetDashboardData():Promise<Record<string, any>>;

export function GetEvents(arg1:number):Promise<Array<Record<string, any>>>;

export function GetPatterns():Promise<Array<Record<string, any>>>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
