// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAutomation(arg1) {
  return window['go']['app']['App']['CreateAutomation'](arg1);
}

export function GetDashboardData() {
  return window['go']['app']['App']['GetDashboardData']();
}

export function GetEvents(arg1) {
  return window['go']['app']['App']['GetEvents'](arg1);
}

export function GetPatterns() {
  return window['go']['app']['App']['GetPatterns']();
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
